### ISSUE TITLE
-O2 optimize compilation，E: Failed to exec: 14

### ISSUE THREAD

**Issue by echizenryoma** [HikaruDY/6relayd#4]
log:

```
I: add Route: 240e:xxxx -> br0
E: Failed to exec: 14
```

**Comment by echizenryoma** [comment]
-fno-toplevel-reorder
disable toplevel-reorder

**Comment by Yamatohimemiya** [comment]
Sorry, these codes are only intended for the Linux distribution "DESLinux" (which has its own syscall, C compiler "desl-cc" and standard C library "DFCRT") environment.

So I can't test and fix it in other environments (Debian, RHEL, etc.) because I don't have them.
